# Name suffix
os_name = win32
DEST_DIR = saldl-${os_name}
BLD_DIR = saldl-${os_name}-build

# mingw-w64 binaries
CC = i686-w64-mingw32-gcc
STRIP = i686-w64-mingw32-strip

include Makefile.mingw.include
