# Name suffix
os_name = win64
DEST_DIR = saldl-${os_name}
BLD_DIR = saldl-${os_name}-build

# mingw-w64 binaries
CC = x86_64-w64-mingw32-gcc
STRIP = x86_64-w64-mingw32-strip
PKG_CONFIG_PATH=/usr/x86_64-w64-mingw32/lib/pkgconfig

include Makefile.mingw.include
