name: CI Workflow
run-name: ${{ github.actor }} is building ${{ github.repository }} using GitHub Actions 🚀
on:
  push
  pull_request
  schedule:
    - cron: '30 18 * * 2'
jobs:
  build_arch:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: update ubuntu
        run: |
          sudo apt update
          sudo apt upgrade
      - name: install build deps
        run: |
          sudo apt install -y --no-install-recommends build-essential pkg-config libcurl4-openssl-dev libevent-dev asciidoc docbook-xml git
      - name: build
        run: |
          python3 waf configure -vv
          python3 waf build -vv
      - name: simple test
        run: |
          readelf -d ./build/saldl
          ./build/saldl -v
          date --date="@$(./build/saldl -I --no-status --stdout 'https://time.akamai.com/?iso/')"
      - run: echo "🍏 This job's status is ${{ job.status }}."
